src/app/components/Button/index.tsx
src/app/components/CurrencyInputPanel/index.tsx
src/app/components/Popover/index.tsx
src/app/components/home/CollateralPanel.tsx
src/app/components/home/LoanPanel.tsx
src/app/components/home/RewardsPanel.tsx
src/app/components/home/WalletPanel.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/components/trade/ReturnICDSection.tsx
src/app/theme/index.tsx
src/app/theme/styled.d.ts

-fix collateral, loan, reward modal style
-fix retire bnUSD dropdown style
-fix liquidity details dropdowns style
-remove the border underneath the final wallet asset in wallet section

improve general styles #24

---

src/app/components/LockBar/index.tsx
src/app/components/home/LoanPanel.tsx

Add Used indicator to the Loan section #73

---

src/app/components/home/PositionDetailPanel.tsx
src/app/theme/index.tsx
src/packages/icon-react/index.tsx
src/store/collateral/hooks.ts
src/store/loan/hooks.ts

Risk Ratio: The bar is not filling properly. #49

---

src/app/components/AddressInputPanel/index.tsx
src/app/components/CurrencyInputPanel/index.tsx
src/app/components/trade/LPPanel.tsx
src/packages/icon-react/utils.ts
src/store/wallet/hooks.ts
src/store/wallet/reducer.ts

Fix input field styles #13

---

src/app/components/trade/LPPanel.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/components/trade/LiquiditySelect.tsx
src/app/components/trade/SwapPanel.tsx
src/app/containers/TradePage/index.tsx
src/constants/currency.ts
src/constants/index.ts
src/packages/BalancedJs/contracts/Baln.ts
src/packages/BalancedJs/contracts/Dex.ts
src/packages/BalancedJs/contracts/contract.ts
src/packages/BalancedJs/contracts/sICX.ts
src/store/liquidity/actions.ts
src/store/liquidity/hooks.ts
src/store/liquidity/reducer.ts
src/store/ratio/hooks.ts

Features Status:
Questions:
1. How do I swap sICX -> ICX? As of now when we select sICX only bnUSD is available for swap destination.
2. Similar to the remaining pairs.

Balanced swap token

---

src/app/components/home/WalletPanel.tsx
src/packages/BalancedJs/contracts/Baln.ts
src/packages/BalancedJs/contracts/bnUSD.ts
src/packages/BalancedJs/contracts/sICX.ts

Transfer tokens, stake BALN & unstake sICX contract calls

---

src/app/components/home/RewardsPanel.tsx
src/packages/BalancedJs/contracts/Rewards.ts

add Claim rewards

---

src/app/components/CurrencyInputPanel/index.tsx

Fix this issue https://github.com/balancednetwork/balanced-network-interface/issues/142

Swap Tab: Fix the wallet

---

src/app/components/trade/SwapPanel.tsx

- On changing pairs, swapOutputAmount update accordingly.
- Input swapOutputAmount -> input amount value will updated with fee included.

Fee and Rate correctly

---

src/app/components/trade/LPPanel.tsx
src/app/components/trade/SwapPanel.tsx
src/app/components/trade/utils.tsx
src/app/containers/TradePage/index.tsx
src/store/liquidity/hooks.ts
src/store/reward/hooks.ts

update fetch refresh liquidity & reward

---

src/app/components/trade/LPPanel.tsx
src/app/components/trade/LiquidityDetails.tsx

Feature: slider for swap & withdraw

---

src/app/components/home/RewardsPanel.tsx
src/store/reward/hooks.ts

feat: add confirm modals in rewards panel

---

src/app/components/ProposalStatusIcon/index.tsx
src/app/containers/ProposalPage/index.tsx

fix: vote status

---

src/app/components/CurrencyInputPanel/index.tsx
src/app/components/Popover/index.tsx
src/app/components/trade/LPPanel.tsx
src/app/components/trade/LiquiditySelect.tsx

Fix: centering DropdownPopper

---

src/app/components/Header/index.tsx
src/app/components/Logo/index.tsx
src/app/components/Popover/index.tsx
src/app/components/Tooltip/index.tsx

Feat: create tooltip without arrow and border

---

src/app/containers/ProposalPage/index.tsx
src/queries/vote/index.ts

fix: add more vote information

---

src/store/swap/reducer.ts

fix: update default swap pair to BALN/bnUSD

---

src/packages/BalancedJs/contracts/Governance.ts
src/queries/vote/index.ts

fix: voting weight

---

src/app/containers/ProposalPage/index.tsx

fix: vote cast text

---

src/queries/reward/index.ts

fix: IUSDC network fee unit

---

src/app/components/home/PositionDetailPanel.tsx

fix rebalancing ui text

---

src/app/components/home/wallets/BALNWallet/StakePanel.tsx
src/app/components/home/wallets/BALNWallet/UnstakePanel.tsx

fix time format

---

src/app/components/trade/SupplyLiquidityModal.tsx
src/constants/pairs.ts

Fix - SupplyLiquidityModal hardcoded & rewards

---

src/constants/tokens.ts
src/queries/swap/index.ts

Refactor: usePriceChartDataQuery - remove hardcoded values

---

src/types/balanced-v1-sdk/entities/trade.ts

fix: minimum to receive

---

src/app/components/trade/SwapPanel.tsx

Addresses issue [#804](https://github.com/balancednetwork/balanced-network-interface/issues/804)

Change Wallet display in Swap to 4 dp

---

src/types/balanced-v1-sdk/entities/trade.ts

Fix: <for> transaction fails for queue

---

src/app/components/trade/SwapPanel.tsx
src/packages/BalancedJs/contracts/Router.ts
src/utils/index.ts

fix: add missing minimumReceive to swapICX

---

src/app/components/home/RewardsPanel.tsx
src/store/reward/hooks.ts

fix: update network fee qualification details

---

src/app/components/home/PositionDetailPanel.tsx

fix: update liquidation price tooltip

---

src/app/components/trade/LiquidityDetails.tsx

feat: hide liquidity details if user has no liquidity provided

---

src/constants/routing.ts

Close #857 
What additional base pairs are needed, do you think? @octocat512

fix: add missing additional base pairs

---

src/app/components/ProposalModal/index.tsx
src/app/containers/NewProposalPage/index.tsx
src/app/containers/ProposalPage/index.tsx

feat: add possibility to change vote

---

src/app/components/AppBar/index.tsx
src/app/components/Form/index.tsx
src/app/components/Pagination/index.tsx
src/app/components/Panel/index.tsx
src/app/components/SearchModal/CurrencyList.tsx
src/app/components/Spinner/index.tsx
src/app/components/Tooltip/index.tsx
src/app/components/WalletModal/index.tsx
src/app/components/home/CollateralPanel.tsx
src/app/components/home/LoanPanel.tsx
src/app/components/home/PositionDetailPanel.tsx
src/app/components/home/TransactionPanel.tsx
src/app/components/home/WalletPanel.tsx
src/app/components/home/wallets/utils.tsx
src/app/components/newproposal/ProposalTypesSelect.tsx
src/app/components/newproposal/RatioInput.tsx
src/app/components/trade/SwapDescription.tsx
src/app/containers/ProposalPage/index.tsx
src/app/theme/index.tsx
src/app/theme/styled.d.ts

Reverts balancednetwork/balanced-network-interface#840

Revert "add: optimise small device ux"

---

src/app/containers/ProposalPage/index.tsx

fix: show voting progress to all users

---

src/app/components/trade/LiquidityDetails.tsx
src/app/containers/TradePage/index.tsx

hide the liquidity details when the swap tab is active

---

src/app/containers/Airdrip/index.tsx

fix: fix heading size on claim page

---

src/app/components/home/RewardsPanel.tsx

fix: remove redundant ledger confirm message

---

src/app/components/TradingViewChart/index.tsx

Adjust the price chart time frames on the Trade page

---

src/app/Routes.tsx
src/app/containers/HomePage/index.tsx
src/app/containers/NewProposalPage/index.tsx
src/app/containers/ProposalPage/index.tsx
src/app/containers/TradePage/index.tsx
src/app/containers/VotePage/index.tsx
src/app/index.tsx

Refactor routes and layout

---

src/app/components/trade/utils.tsx

What are the steps to do after adding text trans?

Add possible missing text trans

---

src/app/components/trade/SwapPanel.tsx

feat: add spacing to wallet label in swap

---

src/app/components/WalletModal/index.tsx
src/app/components/home/LoanPanel.tsx
src/app/components/home/RewardsPanel.tsx
src/app/components/home/WalletPanel.tsx
src/app/components/newproposal/ProposalTypesSelect.tsx
src/app/components/trade/LPDescription.tsx
src/app/components/trade/RebalanceButton.tsx
src/app/components/trade/SwapDescription.tsx
src/app/components/trade/SwapPanel.tsx
src/app/containers/NewProposalPage/index.tsx
src/app/containers/ProposalPage/index.tsx

add missing words

---

src/app/components/trade/LPDescription.tsx

fix: pool description

---

src/app/components/home/CollateralPanel.tsx
src/app/components/home/LoanPanel.tsx
src/app/components/home/RewardsPanel.tsx
src/app/components/home/wallets/BALNWallet/StakePanel.tsx
src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
src/app/components/home/wallets/SendPanel.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/components/trade/SupplyLiquidityModal.tsx
src/app/components/trade/SwapPanel.tsx
src/app/containers/NewProposalPage/index.tsx
src/app/containers/ProposalPage/index.tsx
src/packages/BalancedJs/index.ts
src/store/application/hooks.ts

1.    Login Balanced by Ledger wallet with address hx….01
2.    Login OMM [App | Omm](https://app.omm.finance/#/home)  with the same wallet address as above hx….01
3. Try to perform a transaction on Balanced,
**Actual**: Nothing happened
**Expectation**: Work with any transaction
Renew transport with any transaction need to confirm on Ledger
#932

fix: prevent ledger was deactivated on balanced when user login the same wallet address on another platform

---

src/app/components/home/CollateralPanel.tsx
src/app/components/home/LoanPanel.tsx
src/app/components/home/RewardsPanel.tsx
src/app/components/home/wallets/BALNWallet/StakePanel.tsx
src/app/components/home/wallets/ICXWallet/UnstakePanel.tsx
src/app/components/home/wallets/SICXWallet/DepositPanel.tsx
src/app/components/home/wallets/SICXWallet/UnstakePanel.tsx
src/app/components/home/wallets/SendPanel.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/components/trade/SupplyLiquidityModal.tsx
src/app/components/trade/SwapPanel.tsx
src/app/containers/NewProposalPage/index.tsx
src/app/containers/ProposalPage/index.tsx
src/packages/BalancedJs/index.ts
src/store/application/hooks.ts

Reverts balancednetwork/balanced-network-interface#943

Revert "fix: prevent ledger was deactivated on balanced when user login the same wallet address on another platform"

---

package.json
src/hooks/useLocalStorage.ts
src/packages/BalancedJs/contractSettings.ts
src/packages/BalancedJs/index.ts
src/packages/icon-react/index.tsx
yarn.lock

Reverts balancednetwork/balanced-network-interface#958

Revert "Revert "feat: keep user signed in on refresh""

---

src/hooks/usePools.ts
src/hooks/useQueuePair.ts
src/hooks/useV2Pairs.ts
src/packages/BalancedJs/addresses.ts
src/packages/BalancedJs/contracts/Dex.ts
src/packages/BalancedJs/contracts/Multicall.ts
src/queries/reward/index.ts
src/store/reward/hooks.ts
src/store/swap/trade.ts
src/store/wallet/hooks.ts
src/utils/index.ts

Reverts balancednetwork/balanced-network-interface#966

Revert "Feat/multicall"

---

src/hooks/useLocalStorage.ts
src/packages/icon-react/index.tsx

feat: add user logout after an hour

---

src/app/components/home/TransactionPanel.tsx
src/utils/index.ts

feat: change activity history to two decimal places

---

src/queries/reward/index.ts

- Update range sizes to get user dividends

fix: update range sizes to get user dividends

---

package.json
src/hooks/usePools.ts
src/store/stakedLP/hooks.ts
yarn.lock

Fix wrong decimals to calculate value of usdt/usdc for stakedlp

fix:update wrong decimals of usdt/usdc of stakedlp

---

src/store/stabilityFund/hooks.ts

fix:fix bnusd swap error

---

src/app/components/home/RewardsPanel.tsx
src/queries/reward/index.ts

fix: network fee claim

---

package.json
src/app/components/CurrencyLogo/index.tsx
src/app/components/SearchModal/filtering.ts
src/app/components/TradingViewAdvanced/api/index.ts
src/app/components/TradingViewAdvanced/api/symbols.ts
src/app/components/home/RewardsPanel.tsx
src/app/components/home/TransactionPanel.tsx
src/app/components/home/WalletPanel.tsx
src/app/components/trade/SwapDescription.tsx
src/constants/currency.ts
src/constants/pairs.ts
src/constants/routing.ts
src/constants/tokens.ts
src/hooks/Tokens.ts
src/queries/swap/index.ts
src/store/lists/hooks.ts
src/store/lists/tokenlist.json
src/store/lists/wrappedTokenInfo.ts
src/store/swap/reducer.ts
yarn.lock

Reverts balancednetwork/balanced-network-interface#1046

Revert "Revert "refactor: add default token list""

---

src/store/lists/tokenlist.json

This PR includes:
1.  CROWN token added to `tokenlist.json`.
PR for adding the CROWN icon:
https://github.com/balancednetwork/icons/pull/1

add crown token to token list

---

package.json
yarn.lock

feat: update v1 sdk version

---

README.md
package.json
src/app/components/Popover/index.tsx
src/app/components/SlippageSetting/index.tsx
src/app/components/StabilityFund/index.tsx
src/app/components/trade/LPPanel.tsx
src/app/components/trade/SupplyLiquidityModal.tsx
src/app/components/trade/SwapPanel.tsx
src/app/containers/NewProposalPage/constant.ts
src/app/containers/NewProposalPage/index.tsx
src/store/lists/tokenlist.json
src/store/stabilityFund/hooks.ts
src/store/stabilityFund/reducer.ts
src/store/swap/hooks.ts
yarn.lock

- Update the changes to include fixed bugs and enhancements

Update the changes include fixed bugs and enhancements

---

src/app/components/trade/LPDescription.tsx
src/store/mint/reducer.ts

Update default position of pair and round ICX liquidity

---

src/app/Message.tsx
src/app/components/Banner/index.tsx
src/app/components/CommunityListToggle/index.tsx
src/app/components/List/index.tsx
src/app/components/SearchModal/CurrencySearch.tsx
src/app/components/home/WalletPanel.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/index.tsx
src/constants/tokens.ts
src/hooks/useV2Pairs.ts
src/store/configureStore.ts
src/store/fees/hooks.ts
src/store/lists/actions.ts
src/store/lists/communitylist.json
src/store/lists/hooks.ts
src/store/lists/reducer.ts
src/store/lists/tokenlist.json
src/store/wallet/hooks.ts
src/types/RootState.ts

feat: add community token list

---

src/app/components/home/BBaln/BBalnPanel.tsx

fix: fix lp name boost info formatting

---

src/app/components/home/BBaln/BBalnPanel.tsx

fix: fix conflicting max rewards info

---

package.json
src/app/components/DropdownText/index.tsx
src/app/components/home/BBaln/BBalnPanel.tsx
src/app/components/home/BBaln/utils.ts
src/store/bbaln/hooks.ts
yarn.lock

Fix possibility to keep the same lock time

---

src/store/collateral/hooks.ts
src/store/loan/hooks.ts

Reset collateral and loan UI for empty positions

---

src/app/components/trade/LPDescription.tsx

Show decimals for high price assets in LP description

---

src/app/components/trade/LPPanel.tsx
src/constants/routing.ts

Add BTCB to quotes

---

src/app/components/trade/SwapPanel.tsx
src/constants/misc.ts

Add slippage warning

---

src/app/components/Wallet/wallets/ICXWallet/UnstakePanel.tsx
src/app/components/trade/LPDescription.tsx

Fix sICX unstaking estimation explanation

---

src/app/components/Header/index.tsx
src/app/components/trade/LPDescription.tsx
src/app/components/trade/LPPanel.tsx
src/queries/reward/index.ts

Improve ICX queue UX

---

package.json
src/app/components/home/BBaln/BBalnSlider.tsx
src/app/containers/HomePage/index.tsx
src/app/containers/VotePage/LiveVotingPanel.tsx
src/app/containers/VotePage/styledComponents.tsx
yarn.lock

Update live voting wording

---

src/app/components/home/LoanPanel.tsx
src/app/components/home/PositionDetailPanel.tsx
src/queries/rebalancing/index.ts

Add redemption content

---

src/app/components/Header/index.tsx

Remove notification after claiming unstaked icx

---

src/app/components/trade/LPDescription.tsx

Fix crash while supplying liquidity

---

src/app/containers/VotePage/LiveVotingPanel.tsx
src/app/containers/VotePage/bribeLinks.ts

Add bribe links

---

package.json
src/app/components/trade/LPDescription.tsx
src/app/components/trade/LiquidityDetails.tsx
src/app/components/trade/LiquidityDetails/StakeLPPanel.tsx
src/app/components/trade/LiquidityDetails/WithdrawPanel.tsx
src/queries/backendv2/index.ts
src/queries/reward/index.ts
yarn.lock

Fix rewards estimates based on pool staked LP

---

src/app/components/home/BBaln/BBalnSlider.tsx
src/utils/formatter.ts

Update BALN early withdraw UI

---

src/app/components/bridge/BridgePanel.tsx
src/assets/icons/horizontal-flip.svg

add flip button in the bridge panel

---

src/app/Routes.tsx

fix deep link for the supply tab #1250

---

src/app/components/Header/index.tsx
src/app/components/Notification/TransactionNotification.tsx
src/app/components/WalletModal/index.tsx
src/app/theme/index.tsx

UX/UI
- Change Ledger address loading transition
- Add missing right arrow of pagination for Ledger address modal
Fix
- Cannot sign-in with ledger again after sign-out from ledger
- Cannot sign tx with ledger after refresh the page
- Click on the same pagination on Ledger address modal

Ledger connection flow

---

apps/web/src/app/components/ModalContent/index.tsx
apps/web/src/app/components/WalletModal/index.tsx
apps/web/src/app/components/home/BBaln/BBalnSlider.tsx
apps/web/src/app/components/home/Savings/index.tsx
apps/web/src/app/components/trade/LiquidityDetails/StakeLPPanel.tsx
apps/web/src/app/components/trade/XCallSwapModal.tsx
apps/web/src/app/pages/vote/_components/LieVotingPanel/VotingComponent.tsx

ref: https://github.com/balancednetwork/balanced-network-interface/pull/1284#issuecomment-2049226843

Fix spinner issues

---

apps/web/src/app/Routes.tsx
apps/web/src/app/components/BTP/index.tsx
apps/web/src/app/index.tsx
apps/web/src/app/pages/legacy-bridge/page.tsx
apps/web/src/app/pages/trade/layout.tsx
apps/web/src/locales/en-US.po

https://balanced-network-interface-ph0nyjhal-balanced-dao.vercel.app/legacy-bridge

Move legacy bridge to a separate page

---

apps/web/src/app/components/trade/AllPoolsPanel.tsx
apps/web/src/app/components/trade/LPDescription.tsx
apps/web/src/app/components/trade/LiquidityDetails.tsx

Reverts balancednetwork/balanced-network-interface#1331

Revert "fix: show lp fees APR in user liquidity details (#1201)"

---

apps/web/src/constants/routing.ts

Remove USDS, IUSDC, and BTCB from the list of supply quotes

---

apps/web/src/app/pages/trade/supply/_components/LPPanel.tsx
apps/web/src/app/pages/trade/supply/_components/SupplyLiquidityModal.tsx
apps/web/src/lib/xcall/_hooks/useApproveCallback.tsx
apps/web/src/locales/en-US.po
apps/web/src/locales/es-ES.po
apps/web/src/locales/fr-FR.po
apps/web/src/locales/ko-KR.po
apps/web/src/locales/nl-NL.po
apps/web/src/locales/pl-PL.po
apps/web/src/locales/pseudo.po
apps/web/src/locales/vi-VN.po
apps/web/src/store/mint/hooks.tsx
apps/web/src/store/mint/reducer.ts
apps/web/src/store/wallet/hooks.ts

- remove useAllowHandler
- fix the bug that slider caused a white screen

refactor mint panel

---

apps/stats/src/queries/index.ts
apps/stats/src/sections/BALNSection/queries.ts
packages/balanced-js/src/contracts/Rewards.ts

Fix BALN distribution chart

---

apps/web/src/app/components/home/BBaln/BBalnSlider.tsx
apps/web/src/app/components/home/RewardsPanel/index.tsx
apps/web/src/app/components/home/Savings/index.tsx
apps/web/src/app/pages/trade/supply/_components/AllPoolsPanel.tsx
apps/web/src/app/pages/trade/supply/_components/LiquidityDetails.tsx
apps/web/src/store/savings/hooks.ts

Fix savings rate tooltip

---

apps/web/src/store/lists/tokenlist.json
packages/v1-sdk/src/entities/pair.ts

Add SUI ICON token

---

apps/stats/src/pages/PerformanceDetails/index.tsx
apps/stats/src/pages/PerformanceDetails/sections/EarningSection/index.tsx
apps/stats/src/queries/assetManager/index.ts
apps/stats/src/queries/backendv2.ts
apps/stats/src/queries/burn/index.ts
apps/stats/src/queries/historicalData/index.ts
apps/stats/src/queries/index.ts
apps/stats/src/queries/nol/index.ts
apps/stats/src/sections/CollateralAndLoanSection/BnUSDChart/index.tsx
apps/stats/src/sections/CollateralAndLoanSection/CollateralChart/index.tsx
apps/stats/src/sections/EnshrinmentSection/ICXBurn/index.tsx
apps/stats/src/sections/EnshrinmentSection/NetworkOwnedLiquidity/index.tsx
apps/stats/src/sections/HoldingsOverviewSection/queries.ts
apps/stats/src/sections/WithdrawalLimits/CollateralLimits/index.tsx
apps/stats/src/sections/WithdrawalLimits/ExchangeLimits/index.tsx
apps/stats/src/sections/WithdrawalLimits/StabilityFundLimits/index.tsx

Issue is recorded in the old stats page repo
https://github.com/balancednetwork/balanced-network-info/issues/214

Update stats page

---

apps/stats/src/pages/StatsPage/index.tsx
apps/stats/src/sections/BALNSection/DistributionChart/index.tsx
apps/stats/src/sections/BALNSection/queries.ts
apps/stats/src/sections/CollateralAndLoanSection/BnUSDChart/Chart.tsx
apps/stats/src/sections/CollateralAndLoanSection/BnUSDChart/index.tsx
apps/stats/src/sections/CollateralAndLoanSection/CollateralChart/Chart.tsx
apps/stats/src/sections/CollateralAndLoanSection/CollateralChart/index.tsx
apps/web/src/app/components/home/BBaln/BBalnSlider.tsx
apps/web/src/app/components/home/RewardsPanel/LPRewards.tsx
apps/web/src/app/components/home/RewardsPanel/NetworkFeesRewards.tsx
apps/web/src/app/components/home/RewardsPanel/PositionRewardsInfo.tsx
apps/web/src/app/components/home/RewardsPanel/SavingsRewards.tsx
apps/web/src/app/components/home/RewardsPanel/index.tsx
apps/web/src/app/components/home/Savings/index.tsx
apps/web/src/store/bbaln/hooks.ts
apps/web/src/store/savings/hooks.ts

New BALN allocation related update

---

apps/web/src/xwagmi/constants/xChains.ts
apps/web/src/xwagmi/xchains/sui/SuiXPublicClient.ts

Reverts balancednetwork/balanced-network-interface#1490

Revert "update sui fee"

---

apps/web/src/store/swap/reducer.ts

Set default swap to SUI bnUSD

---

apps/web/src/app/components/home/PositionDetailPanel.tsx
apps/web/src/store/wallet/hooks.ts

Update liquidation tooltip

---

apps/web/src/app/pages/trade/supply/_components/AllPoolsPanel.tsx
apps/web/src/app/pages/trade/supply/_components/LiquidityPoolsPanel.tsx
apps/web/src/queries/backendv2/index.ts

Show all pools instead of just the incentivised ones

---

apps/web/src/app/components/CollateralTypeSwitcher/CollateralTypeList.tsx
apps/web/src/app/components/CurrencyInputPanel/index.tsx
apps/web/src/app/components/SearchModal/CurrencyList.tsx
apps/web/src/app/components/SearchModal/CurrencySearch.tsx
apps/web/src/app/components/SearchModal/filtering.ts
apps/web/src/app/components/TradingViewAdvanced/api/history.ts
apps/web/src/app/components/TradingViewAdvanced/api/index.ts
apps/web/src/app/components/TradingViewChart/index.tsx
apps/web/src/app/pages/trade/bridge/_components/BridgeActivity.tsx
apps/web/src/app/pages/trade/bridge/_components/BridgeTransferForm.tsx
apps/web/src/app/pages/trade/bridge/_components/XTransferModal.tsx
apps/web/src/app/pages/trade/supply/_components/AllPoolsPanel.tsx
apps/web/src/app/pages/trade/xswap/_components/AdvancedSwapDetails.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapDescription.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapModal.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapPanel.tsx
apps/web/src/app/pages/trade/xswap/_components/TokenList/TokenItem.tsx
apps/web/src/app/pages/trade/xswap/_components/TokenList/index.tsx
apps/web/src/app/pages/trade/xswap/_components/XSwapModal.tsx
apps/web/src/constants/tokens.ts
apps/web/src/locales/en-US.po
apps/web/src/locales/es-ES.po
apps/web/src/locales/fr-FR.po
apps/web/src/locales/ko-KR.po
apps/web/src/locales/nl-NL.po
apps/web/src/locales/pl-PL.po
apps/web/src/locales/pseudo.po
apps/web/src/locales/vi-VN.po
apps/web/src/utils/formatter.ts
apps/web/src/utils/xTokens.ts

Trade page enhancements

---

apps/web/src/app/components/CurrencyInputPanel/DollarValue.tsx
apps/web/src/app/components/CurrencyInputPanel/index.tsx

Add dollar value to currency inputs

---

apps/web/src/app/components/Wallet/index.tsx

Add empty wallet state

---

apps/hswap/src/app/components/WalletModal/index.tsx
apps/hswap/src/app/components2/Modal/index.tsx
apps/hswap/src/app/components2/WalletLogo/index.tsx

remove console warnings

---

apps/hswap/README.md
apps/stats/README.md
apps/stats/index.html
apps/stats/src/constants/links.ts
apps/stats/src/queries/backendv2.ts
apps/web/README.md
apps/web/index.html

Update x handle

---

apps/hswap/src/queries/backendv2/index.ts
apps/stats/src/queries/backendv2.ts
apps/web/src/queries/backendv2/index.ts

Hotfix XLM trend line

---

apps/stats/src/sections/TokenSection.tsx
apps/web/src/app/components/AssetManagerTokenBreakdown/index.tsx
apps/web/src/app/components/BridgeLimitWarning/index.tsx
apps/web/src/app/components/WithdrawalLimitInfo/index.tsx
apps/web/src/app/components/WithdrawalLimitWarning/index.tsx
apps/web/src/app/pages/trade/bridge/_components/BridgeTransferForm.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapCommitButton.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapPanel.tsx
apps/web/src/app/pages/trade/xswap/_components/TokenList/TokenItem.tsx
apps/web/src/app/pages/trade/xswap/_components/TokenList/index.tsx
apps/web/src/locales/en-US.po
apps/web/src/locales/es-ES.po
apps/web/src/locales/fr-FR.po
apps/web/src/locales/ko-KR.po
apps/web/src/locales/nl-NL.po
apps/web/src/locales/pl-PL.po
apps/web/src/locales/pseudo.po
apps/web/src/locales/vi-VN.po
apps/web/src/queries/backendv2/index.ts
apps/web/src/store/bridge/hooks.tsx
apps/web/src/store/swap/hooks.ts
apps/web/src/types/index.ts

Implement withdrawal limits notice

---

apps/web/src/app/components/home/PositionDetailPanel.tsx
apps/web/src/constants/tokens.ts
apps/web/src/store/lists/tokenlist.json
packages/xwagmi/src/constants/xChains.ts
packages/xwagmi/src/constants/xTokens.ts

Reverts balancednetwork/balanced-network-interface#1567

Revert "add mSUI"

---

apps/web/src/app/components/home/PositionDetailPanel.tsx
apps/web/src/constants/tokens.ts
apps/web/src/store/lists/tokenlist.json
packages/xwagmi/src/constants/xChains.ts
packages/xwagmi/src/constants/xTokens.ts

Reverts balancednetwork/balanced-network-interface#1614

Revert "Revert "add mSUI""

---

apps/web/src/app/components/Header/index.tsx
apps/web/src/app/components/Wallet/ICONWallets/SendPanel.tsx
apps/web/src/app/components/Wallet/SingleChainBalanceItem.tsx
apps/web/src/app/components/Wallet/useClaimableICX.ts

Add support for BTC claim

---

apps/web/src/app/pages/trade/supply/_components/LiquidityDetails.tsx

Reverts balancednetwork/balanced-network-interface#1611

Revert "hide PoolRecordQ temporarily"

---

apps/web/src/app/components/CollateralTypeSwitcher/CollateralTypeList.tsx

Fix collateral panel search

---

apps/web/src/store/swap/hooks.ts

Improve intent fee handling

---

apps/web/src/app/components/CollateralTypeSwitcher/SingleChainItemOverview.tsx
apps/web/src/app/components/CurrencyInputPanel/index.tsx
apps/web/src/app/components/SearchModal/CurrencySearch.tsx
apps/web/src/app/components/SearchModal/XChainFilter.tsx
apps/web/src/app/components/home/BBaln/BBalnSlider.tsx
apps/web/src/app/components/home/RewardsPanel/index.tsx
apps/web/src/app/components/home/Savings/index.tsx
apps/web/src/app/components/home/_components/SavingsChainSelector/index.tsx
apps/web/src/app/pages/trade/supply/_components/LPPanel.tsx
apps/web/src/app/pages/trade/supply/_components/LiquidityDetails.tsx
apps/web/src/app/pages/trade/supply/_components/LiquidityDetails/SuggestStakingLPModal.tsx
apps/web/src/app/pages/trade/xswap/_components/MMSwapInfo.tsx
apps/web/src/app/pages/trade/xswap/_components/SwapInfo.tsx
apps/web/src/hooks/useSortXChains.ts
apps/web/src/hooks/useSortXCollateralTypes.ts
apps/web/src/hooks/useXCallGasChecker.tsx
apps/web/src/locales/en-US.po
apps/web/src/locales/es-ES.po
apps/web/src/locales/fr-FR.po
apps/web/src/locales/ko-KR.po
apps/web/src/locales/nl-NL.po
apps/web/src/locales/pl-PL.po
apps/web/src/locales/pseudo.po
apps/web/src/locales/vi-VN.po
apps/web/src/store/collateral/hooks.ts
apps/web/src/store/mint/hooks.tsx
apps/web/src/store/reward/hooks.ts
apps/web/src/store/reward/reducer.ts
apps/web/src/utils/index.ts
packages/xwagmi/src/constants/xTokens.ts

Add improvements and fix bugs

---

apps/stats/src/components/Footer/index.tsx
apps/stats/src/constants/links.ts

Add privacy policy link to stats

---

apps/web/src/lib/intent.tsx

Reverts balancednetwork/balanced-network-interface#1707

Revert "Disable icon intents"
